### ISSUE TITLE
Error when translating Russian .srt file

### ISSUE THREAD

**Issue by MilDen** [pepri/subtitles-editor#8] opened 2020-12-16 23:38 UTC
Hello, I just started working with subtitles so this is maybe an error on my side, but when I try to translate srt file that is on Russian I get an error with message "Command 'Subtitles: Translate' resulted in an error (An unknown error occurred. Please consult the log for more details.)". But the logs are showing nothing useful.

I have tried English and Serbian subtitles and they are working correctly. It works the other way around it translates English to Russian. But Russian wont translate to any language.

**Comment by pepri** [comment] 2020-12-17 03:48
Confirmed - I am able to reproduce. Thanks for reporting the issue! 

The issue happens because of the length of the URL when calling the translation service. Current implementation limits the length based on the string length before it is URI-encoded. This works for languages that have mostly ASCII characters in it that do not have to be URI-encoded.

It is fixed in 1.1.3. I added URI-encoding into length calculation and adjusted the limit a bit.

**Closed by pepri** 2020-12-17 03:48 UTC
