### ISSUE TITLE
Frame numbers are being translated as well

### ISSUE THREAD

**Issue by rewebit** [pepri/subtitles-editor#13] opened 2021-05-18 13:53 UTC
Hello,

very nice tool. Just found it and it looks like it will save a lot of work for me. Really appreciate this extension. When running the command: Subtitles: Translate  the resulting language file has the frame numbers replaced in some cases. The replacement of the numbers, is into the text version of the number in the new language. See Frame 2 below. Thank you for checking this out.

English:
1
00:00:00,000 --> 00:00:01,100

2
00:00:01,100 --> 00:00:06,000
This video will cover the points of the backend interface. Once you've logged

German:
1
00:00:00,000 --> 00:00:01,100

Zwei
00:00:01,100 --> 00:00:06,000
Dieses Video behandelt die Punkte der Backend-Oberfläche. Nach dem Einloggen

**Comment by pepri** [comment] 2021-05-19 04:21
Hi,

I tried reproduce the issue by copying the text from your comment, pasting it into VS Code, and executing the translation command. Unfortunately, I am unable to reproduce.

Can you provide a file that I could use to reproduce the behavior?

Thanks!

**Comment by rewebit** [comment] 2021-05-19 08:22
Hello Peter,

One of my teammates took a quick look at this and found the issue. The problem is if a file is converted from the base language to a second language and then a third. When the second translation is done, or a translation of a translation, this is where the issue creeps in.

I have attached a test file for your review. Also a file with the error. please note, Github does not support the .srt file type, so the files have been changed to the .txt file type to allow for upload. please change these back to .srt for use.

[en_test_file.txt](https://github.com/pepri/subtitles-editor/files/6507027/en_test_file.txt)
[en-es-en_test_file.txt](https://github.com/pepri/subtitles-editor/files/6507028/en-es-en_test_file.txt)

The base file is English. The error file is translated into Spanish, and then back into English.

**Comment by pepri** [comment] 2021-05-20 07:09
Thanks for the steps to reproduce the issue. I updated the translation to explicitly skip sequence numbers and also blank lines. I verified that after applying the fix the translation works correctly. 

This issue is fixed in 1.1.5. Thanks!

**Closed by pepri** 2021-05-20 07:09 UTC
